# Generated by Django 3.2.13 on 2022-05-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0004_auto_20220528_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfo',
            name='bears',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='bulls',
        ),
    ]
